# Generated by Django 4.2.16 on 2026-09-26 23:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_refund_product_cost_price_product_min_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='SUR', max_length=200)),
                ('legal_name', models.CharField(default='SIRIUS2010.doo Banja Luka', max_length=200)),
                ('address', models.CharField(default='Prvog Krajiškog Korpusa 18', max_length=200)),
                ('city', models.CharField(default='Banja Luka', max_length=100)),
                ('postal_code', models.CharField(default='78000', max_length=20)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('jib', models.CharField(blank=True, default='', max_length=20, verbose_name='JIB')),
                ('pib', models.CharField(blank=True, default='', max_length=20, verbose_name='PIB')),
                ('mb', models.CharField(blank=True, default='', max_length=20, verbose_name='MB')),
                ('business_unit_id', models.CharField(blank=True, default='4402692070009', max_length=30)),
                ('pos_id', models.CharField(blank=True, default='NOT APPLICABLE', max_length=50)),
                ('store_name', models.CharField(blank=True, default='SIRIUS2010 doo Banja Luka', max_length=200)),
                ('receipt_type', models.CharField(default='MALOPRODAJNI FISKALNI RAČUN', max_length=100)),
                ('header_text', models.TextField(blank=True, default='')),
                ('footer_text', models.TextField(blank=True, default='HVALA NA POSJETI !\nPOS')),
                ('paper_width', models.IntegerField(choices=[(58, '58mm'), (80, '80mm')], default=80)),
                ('font_family', models.CharField(default='Share Tech Mono', max_length=100)),
                ('font_size', models.IntegerField(default=11)),
                ('line_height', models.DecimalField(decimal_places=2, default=Decimal('1.35'), max_digits=4)),
                ('letter_spacing', models.DecimalField(decimal_places=2, default=Decimal('0.40'), max_digits=4)),
                ('show_logo', models.BooleanField(default=False)),
                ('show_address', models.BooleanField(default=True)),
                ('show_phone', models.BooleanField(default=False)),
                ('show_email', models.BooleanField(default=False)),
                ('show_jib', models.BooleanField(default=True)),
                ('show_pib', models.BooleanField(default=True)),
                ('show_operator', models.BooleanField(default=True)),
                ('show_payment_method', models.BooleanField(default=True)),
                ('show_tax', models.BooleanField(default=True)),
                ('show_qr', models.BooleanField(default=False)),
                ('show_barcode', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Receipt Settings',
                'verbose_name_plural': 'Receipt Settings',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='kom', max_length=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='change_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='eo_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('SALE_CREATE', 'Kreiranje prodaje'), ('SALE_CHECKOUT', 'Završetak prodaje'), ('SALE_CANCEL', 'Otkazivanje prodaje'), ('SALE_REFUND', 'Refundacija'), ('SALE_DISCOUNT', 'Popust na računu'), ('PRODUCT_CREATE', 'Kreiranje proizvoda'), ('PRODUCT_UPDATE', 'Izmjena proizvoda'), ('PRODUCT_DELETE', 'Brisanje proizvoda'), ('PRICE_CHANGE', 'Izmjena cijene'), ('STOCK_CHANGE', 'Izmjena stanja'), ('SETTINGS_CHANGE', 'Izmjena podešavanja')], max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('17.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='refund',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Gotovina'), ('CARD', 'Kartica')], default='CASH', max_length=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Gotovina'), ('CARD', 'Kartica'), ('SPLIT', 'Split')], default='CASH', max_length=10),
        ),
    ]
