DEFAULT_RECEIPT_SETTINGS = {
    'business_name': 'SUR',
    'legal_name': 'SIRIUS2010.doo Banja Luka',
    'address': 'Prvog Krajiškog Korpusa 18',
    'city': 'Banja Luka',
    'postal_code': '78000',
    'phone': '',
    'email': '',
    'jib': '',
    'pib': '',
    'mb': '',
    'business_unit_id': '4402692070009',
    'pos_id': 'NOT APPLICABLE',
    'store_name': 'SIRIUS2010 doo Banja Luka',
    'receipt_type': 'MALOPRODAJNI FISKALNI RAČUN',
    'header_text': '',
    'footer_text': 'HVALA NA POSJETI !\nPOS',
    'paper_width': 80,
    'font_family': 'Share Tech Mono',
    'font_size': 11,
    'line_height': 1.35,
    'letter_spacing': 0.4,
    'show_logo': False,
    'show_address': True,
    'show_phone': False,
    'show_email': False,
    'show_jib': True,
    'show_pib': True,
    'show_operator': True,
    'show_payment_method': True,
    'show_tax': True,
    'show_qr': False,
    'show_barcode': True,
}